(deftheme Breath2
  "A rough port of Manjaro's Breath2 Konsole theme to Emacs")

;; Major WIP
;; WTFPL
;; Written by Rick Elrod

(custom-theme-set-faces
 'Breath2
 '(cursor ((t (:background "#149678"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#4dd0e1"))))
 '(highlight ((t (:inverse-video nil :background "#37474f"))))
 '(region ((t (:background "#555555"))))
 '(shadow ((t (:foreground "#b0bec5"))))
 '(secondary-selection ((t (:background "#bf616a"))))
 '(trailing-whitespace ((t (:underline nil :inverse-video t :foreground "#4C566A" :background "red"))))
 '(font-lock-builtin-face ((t (:foreground "#9b59b6"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7f8c8d"))))
 '(font-lock-comment-face ((t (:foreground "#7f8c8d"))))
 '(font-lock-constant-face ((t (:foreground "#1abc9c"))))
 '(font-lock-doc-face ((t (:foreground "#b65619"))))
 '(font-lock-function-name-face ((t (:foreground "#3daee9"))))
 '(font-lock-keyword-face ((t (:foreground "#9b59b6"))))
 '(font-lock-negation-char-face ((t (:foreground "#4dd0e1"))))
 '(font-lock-preprocessor-face ((t (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#fff59d"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#b39ddb"))))
 '(font-lock-string-face ((t (:foreground "#44853a"))))
 '(font-lock-type-face ((t (:foreground "#1d99f3"))))
 '(font-lock-variable-name-face ((t (:foreground "#b65619"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#f36c60"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#263238"))))
 '(header-line ((t (:foreground "#b39ddb" :inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#ffffff" :background "#1c1f26"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#ffffff"))))
 '(mode-line-emphasis ((t (:slant italic :foreground "#ffffff"))))
 '(mode-line-highlight ((t (:box nil :foreground "#b39ddb"))))
 '(mode-line-inactive ((t (:weight normal :box nil :foreground "#a7adba" :background "#1c1f26" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#ffffff" :background "#8bc34a"))))
 '(isearch-fail ((t (:inverse-video t :background "#263238" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((t (:inverse-video nil :foreground "#263238" :background "#8bc34a"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:family "Meslo LG S" :foundry "PfEd" :width normal :height 98 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#17a88b" :background "#1e2229" :stipple nil :inherit nil)))))

(provide-theme 'Breath2)
